QuanLyNhanSu/Models/SlideImage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class SlideImage
    {
        public int id { get; set; }
        //[Required(ErrorMessage = "Phải chọn hình ảnh ")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg)*$", ErrorMessage = "File không hợp lệ(png, jpg)")]
        public string src { get; set; }
        public string alt { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> create_date { get; set; } = DateTime.Now;//by C# v6
        public Nullable<System.DateTime> update_date { get; set; } = DateTime.Now;//by C# v6
    }
}

QuanLyNhanSu/Areas/admin/Controllers/SlideImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class SlideImagesController : Controller
    {
        private QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();

        // GET: admin/SlideImages
        public ActionResult Index()
        {
            return View(db.SlideImages.ToList());
        }

        // GET: admin/SlideImages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SlideImage slideImage = db.SlideImages.Find(id);
            if (slideImage == null)
            {
                return HttpNotFound();
            }
            return View(slideImage);
        }

        // GET: admin/SlideImages/Create
        public ActionResult Create()
        {
            return View(new SlideImage());
        }

        // POST: admin/SlideImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,filePost,alt,title,create_date,update_date")] SlideImage slideImage, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {
                //if (file.ContentLength > 0)
                //{
                //    var fileName = Path.GetFileName(file.FileName);
                //    var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                //    file.SaveAs(path);
                //}

                //if (us.HinhAnh != null)
                //{
                //    HinhAnh.SaveAs(HttpContext.Server.MapPath("~/Content/images/")
                //                                             + HinhAnh.FileName);
                //    up.HinhAnh = HinhAnh.FileName;
                //    us.HinhAnh = HinhAnh.FileName;
                //    //user.Image = userVal.Image;
                //}

                //var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), slideImage.src);
                imgFile.SaveAs(HttpContext.Server.MapPath("~/Content/images/") + imgFile.FileName);

                slideImage.src = imgFile.FileName;
                db.SlideImages.Add(slideImage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slideImage);
        }

        // GET: admin/SlideImages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SlideImage slideImage = db.SlideImages.Find(id);
            if (slideImage == null)
            {
                return HttpNotFound();
            }
            return View(slideImage);
        }

        // POST: admin/SlideImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,src,alt,title,create_date,update_date")] SlideImage slideImage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(slideImage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slideImage);
        }

        //// GET: admin/SlideImages/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    SlideImage slideImage = db.SlideImages.Find(id);
        //    if (slideImage == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(slideImage);
        //}

        // POST: admin/SlideImages/Delete/5
        [ ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SlideImage slideImage = db.SlideImages.Find(id);
            db.SlideImages.Remove(slideImage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyNhanSu/Controllers/SlideImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;

namespace QuanLyNhanSu.Controllers
{
    public class SlideImagesController : Controller
    {
        private QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();

        // GET: SlideImages
        public async Task<ActionResult> Index()
        {
            return View(await db.SlideImages.ToListAsync());
        }

        // GET: SlideImages/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SlideImage slideImage = await db.SlideImages.FindAsync(id);
            if (slideImage == null)
            {
                return HttpNotFound();
            }
            return View(slideImage);
        }

        // GET: SlideImages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SlideImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,src,alt,title,create_date,update_date")] SlideImage slideImage)
        {
            if (ModelState.IsValid)
            {
                db.SlideImages.Add(slideImage);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(slideImage);
        }

        // GET: SlideImages/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SlideImage slideImage = await db.SlideImages.FindAsync(id);
            if (slideImage == null)
            {
                return HttpNotFound();
            }
            return View(slideImage);
        }

        // POST: SlideImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,src,alt,title,create_date,update_date")] SlideImage slideImage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(slideImage).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(slideImage);
        }

        // GET: SlideImages/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SlideImage slideImage = await db.SlideImages.FindAsync(id);
            if (slideImage == null)
            {
                return HttpNotFound();
            }
            return View(slideImage);
        }

        // POST: SlideImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SlideImage slideImage = await db.SlideImages.FindAsync(id);
            db.SlideImages.Remove(slideImage);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyNhanSu/Areas/admin/Views/SlideImages/Create.cshtml
@model QuanLyNhanSu.Models.SlideImage

@{
    ViewBag.Title = "slide images";
}

@using (Html.BeginForm("Create", "SlideImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SlideImage</h4>
        <hr />
        @Html.ValidationSummary(true)
        @*@Html.ValidationSummary(false, "", new { @class = "text-danger" })*@
        @*<div class="form-group">
                @Html.LabelFor(model => model.src, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.src, new { type = "file", name = "imgFile" })
                    @Html.ValidationMessageFor(model => model.src)
                </div>
            </div>*@


        <!--hinh anh-->
        <div class="form-group">
            <div class="control-label  col-md-2 col-sm-2">
                <label>Slide image</label>
            </div>
            <div class="col-md-4 col-sm-10">
                <input class="form-control" required type="file" name="imgFile">
                @Html.ValidationMessageFor(model => model.src, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label  col-md-2 col-sm-2">
                <label>Thẻ mô tả</label>
            </div>
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.alt, new { @class = "form-control" })*@
                <input class="form-control" type="text" name="alt" value="@Model.alt" />
                @*@Html.ValidationMessageFor(model => model.alt)*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.title, new { @class = "form-control" })*@
                <input class="form-control" type="text" name="title" value="@Model.title" />
                @Html.ValidationMessageFor(model => model.title)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index",null,new {@class="btn btn-primary" })
</div>

QuanLyNhanSu/Areas/admin/Views/SlideImages/Delete.cshtml
@model QuanLyNhanSu.Models.SlideImage

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>SlideImage</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.src)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.src)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.alt)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.alt)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.create_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.create_date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.update_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.update_date)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

QuanLyNhanSu/Areas/admin/Views/SlideImages/Details.cshtml
@model QuanLyNhanSu.Models.SlideImage

@{
    ViewBag.Title = "Slide images";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>SlideImage</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.src)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.src)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.alt)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.alt)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.create_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.create_date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.update_date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.update_date)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

QuanLyNhanSu/Areas/admin/Views/SlideImages/Edit.cshtml
@model QuanLyNhanSu.Models.SlideImage

@{
    ViewBag.Title = "Slide images";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>SlideImage</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.src)
        @Html.HiddenFor(model => model.create_date)


        <div class="form-group">
            @Html.LabelFor(model => model.alt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alt)
                @Html.ValidationMessageFor(model => model.alt)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title)
                @Html.ValidationMessageFor(model => model.title)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
<div>
    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-primary" })
</div>
</body>
</html>

QuanLyNhanSu/Areas/admin/Views/SlideImages/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.SlideImage>

@{
    ViewBag.Title = "Slide images";
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Slides
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-user"></i>Slides
            </li>
        </ol>
    </div>
</div>
<p>
    @Html.ActionLink("Thêm mới", "Create", null, // <-- Route value
                 new { @class = "btn btn-primary" })
</p>
<div class="table-responsive">
    <table id="table-taikhoan" class="table table-striped table-hover table-bordered table-responsive ">
        <tr class="success">
            <th>
                Images
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alt)
            </th>
            <th>
                <div class="control-label">
                    <label>Tiêu đề</label>
                </div>
            </th>
            <th>
                <div class="control-label">
                    <label>Ngày tạo</label>
                </div>
            </th>
            <th>
                <div class="control-label">
                    <label>Ngày cập nhật</label>
                </div>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/Content/images/@item.src" class="img-circle img-responsive img-thumbnail" style="width:50px;height:50px" onclick="showImagePreview('@item.src')" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.alt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.create_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.update_date)
                </td>
                <td>

                    <a class="btn btn-warning" href="@Url.Action("Edit", "SlideImages", new {@id = @item.id })"><i class="fa fa-pencil-square-o x5" aria-hidden="true">Sửa</i></a>
                    @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@item.id">
                        Xóa
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="@item.id" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content text-center">
                                <div class="modal-body">
                                    <p>Bạn muốn xóa @item.id+@item.alt?</p>
                                </div>
                                <a class="btn btn-danger" href="@Url.Action("Delete", "SlideImages", new { id = @item.id })">
                                    <span aria-hidden="true"><i class="fa fa-trash-o">Xóa</i></span>
                                </a>
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Hủy</button>
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
        }

    </table>
</div>

    <div class="modal fade" id="imagePreviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <img id="imagePreview" src="" class="img-responsive img-thumbnail" />
                </div>
            </div>
        </div>
    </div>
    <style>
        td img:hover {
            cursor: zoom-in;
        }
    </style>

    <script>

        $(document).ready(function () {
            $("#table-taikhoan").DataTable();
        });

        function showImagePreview(srcImage) {
            $el = $('<button type="button" id="showModel" class="btn btn-primary" data-toggle="modal" data-target="#imagePreviewModal"></button>');
            $('body').append($el);
            $("#imagePreview").attr('src', "/Content/images/" + srcImage);
            $("#showModel").click();
        }

    </script>